from __future__ import annotations

from shared.contracts import ActionRegistryItem, ExecutionMode, Intent


def build_default_action_registry() -> list[ActionRegistryItem]:
    return [
        ActionRegistryItem(
            intent=Intent.GET_STATUS.value,
            label="Get status",
            description="Read device status via Webex cloud xAPI.",
            supported_modes=[ExecutionMode.SEPARATED, ExecutionMode.ALL_LLM],
            approval_required_by_default=False,
        ),
        ActionRegistryItem(
            intent=Intent.GET_ENVIRONMENT_INFO.value,
            label="Get environment info",
            description="Read device-reported environment sensor metrics via Webex cloud xAPI.",
            supported_modes=[ExecutionMode.SEPARATED, ExecutionMode.ALL_LLM],
            approval_required_by_default=False,
        ),
        ActionRegistryItem(
            intent=Intent.GET_CAMERA_MODE.value,
            label="Get camera mode",
            description="Read the current device-reported camera mode via Webex cloud xAPI.",
            supported_modes=[ExecutionMode.SEPARATED, ExecutionMode.ALL_LLM],
            approval_required_by_default=False,
        ),
        ActionRegistryItem(
            intent=Intent.GET_ROOM_BOOKING.value,
            label="Get room booking",
            description="Read current and next room-booking and OBTP state via Webex cloud xAPI.",
            supported_modes=[ExecutionMode.SEPARATED, ExecutionMode.ALL_LLM],
            approval_required_by_default=False,
        ),
        ActionRegistryItem(
            intent=Intent.LIST_DEVICES.value,
            label="List devices",
            description="List organization devices via Webex cloud inventory.",
            supported_modes=[ExecutionMode.SEPARATED, ExecutionMode.ALL_LLM],
            approval_required_by_default=False,
        ),
        ActionRegistryItem(
            intent=Intent.WEBEX_JOIN.value,
            label="Webex join",
            description="Join a Webex meeting from the target device.",
            supported_modes=[ExecutionMode.SEPARATED, ExecutionMode.ALL_LLM],
            approval_required_by_default=True,
        ),
        ActionRegistryItem(
            intent=Intent.JOIN_OBTP.value,
            label="Join OBTP",
            description="Join the next joinable scheduled meeting from the target device.",
            supported_modes=[ExecutionMode.SEPARATED, ExecutionMode.ALL_LLM],
            approval_required_by_default=True,
        ),
        ActionRegistryItem(
            intent=Intent.DIAL.value,
            label="Dial",
            description="Start a generic call or SIP dial from the target device.",
            supported_modes=[ExecutionMode.SEPARATED, ExecutionMode.ALL_LLM],
            approval_required_by_default=True,
        ),
        ActionRegistryItem(
            intent=Intent.HANG_UP.value,
            label="Hang up",
            description="Disconnect the current call on the target device.",
            supported_modes=[ExecutionMode.SEPARATED, ExecutionMode.ALL_LLM],
            approval_required_by_default=True,
        ),
        ActionRegistryItem(
            intent=Intent.SEND_DTMF.value,
            label="Send DTMF",
            description="Send DTMF tones on the target device call.",
            supported_modes=[ExecutionMode.SEPARATED, ExecutionMode.ALL_LLM],
            approval_required_by_default=True,
        ),
        ActionRegistryItem(
            intent=Intent.SET_MICROPHONE_MUTE.value,
            label="Microphone mute",
            description="Mute or unmute microphones on the target device.",
            supported_modes=[ExecutionMode.SEPARATED, ExecutionMode.ALL_LLM],
            approval_required_by_default=True,
        ),
        ActionRegistryItem(
            intent=Intent.SET_MICROPHONE_MODE.value,
            label="Microphone mode",
            description="Change microphone processing mode on the target device.",
            supported_modes=[ExecutionMode.SEPARATED, ExecutionMode.ALL_LLM],
            approval_required_by_default=True,
        ),
        ActionRegistryItem(
            intent=Intent.SET_VOLUME.value,
            label="Set volume",
            description="Adjust the target device volume.",
            supported_modes=[ExecutionMode.SEPARATED, ExecutionMode.ALL_LLM],
            approval_required_by_default=True,
        ),
        ActionRegistryItem(
            intent=Intent.SET_VIDEO_MUTE.value,
            label="Video mute",
            description="Mute or unmute the main video feed on the target device.",
            supported_modes=[ExecutionMode.SEPARATED, ExecutionMode.ALL_LLM],
            approval_required_by_default=True,
        ),
        ActionRegistryItem(
            intent=Intent.SET_SELFVIEW.value,
            label="Selfview",
            description="Enable or disable selfview on the target device.",
            supported_modes=[ExecutionMode.SEPARATED, ExecutionMode.ALL_LLM],
            approval_required_by_default=True,
        ),
        ActionRegistryItem(
            intent=Intent.SET_CAMERA_MODE.value,
            label="Camera mode",
            description="Set a tightly scoped camera tracking mode on the target device when device-reported capability permits it.",
            supported_modes=[ExecutionMode.SEPARATED, ExecutionMode.ALL_LLM],
            approval_required_by_default=True,
        ),
        ActionRegistryItem(
            intent=Intent.SET_LAYOUT.value,
            label="Layout change",
            description="Change the active video layout on the target device.",
            supported_modes=[ExecutionMode.SEPARATED, ExecutionMode.ALL_LLM],
            approval_required_by_default=True,
        ),
        ActionRegistryItem(
            intent=Intent.SET_PRESENTATION.value,
            label="Presentation",
            description="Start or stop presentation on the target device.",
            supported_modes=[ExecutionMode.SEPARATED, ExecutionMode.ALL_LLM],
            approval_required_by_default=True,
        ),
        ActionRegistryItem(
            intent=Intent.SWITCH_INPUT_SOURCE.value,
            label="Input source switch",
            description="Switch the main video input source on the target device.",
            supported_modes=[ExecutionMode.SEPARATED, ExecutionMode.ALL_LLM],
            approval_required_by_default=True,
        ),
        ActionRegistryItem(
            intent=Intent.ASSIGN_MATRIX.value,
            label="Matrix assign",
            description="Assign a video matrix source to an output on the target device.",
            supported_modes=[ExecutionMode.SEPARATED, ExecutionMode.ALL_LLM],
            approval_required_by_default=True,
        ),
        ActionRegistryItem(
            intent=Intent.UNASSIGN_MATRIX.value,
            label="Matrix unassign",
            description="Unassign a video matrix source from an output on the target device.",
            supported_modes=[ExecutionMode.SEPARATED, ExecutionMode.ALL_LLM],
            approval_required_by_default=True,
        ),
        ActionRegistryItem(
            intent=Intent.SWAP_MATRIX.value,
            label="Matrix swap",
            description="Swap two video matrix outputs on the target device.",
            supported_modes=[ExecutionMode.SEPARATED, ExecutionMode.ALL_LLM],
            approval_required_by_default=True,
        ),
        ActionRegistryItem(
            intent=Intent.SET_DISPLAY_MODE.value,
            label="Display mode",
            description="Change the monitor layout mode on the target device.",
            supported_modes=[ExecutionMode.SEPARATED, ExecutionMode.ALL_LLM],
            approval_required_by_default=True,
        ),
        ActionRegistryItem(
            intent=Intent.SET_DISPLAY_ROLE.value,
            label="Display role",
            description="Change a monitor role for a device display connector.",
            supported_modes=[ExecutionMode.SEPARATED, ExecutionMode.ALL_LLM],
            approval_required_by_default=True,
        ),
        ActionRegistryItem(
            intent=Intent.ACTIVATE_CAMERA_PRESET.value,
            label="Camera preset",
            description="Activate a saved camera preset on the target device.",
            supported_modes=[ExecutionMode.SEPARATED, ExecutionMode.ALL_LLM],
            approval_required_by_default=True,
        ),
        ActionRegistryItem(
            intent=Intent.ADJUST_CAMERA_POSITION.value,
            label="Camera position",
            description="Move or zoom a specific camera on the target device using discrete cloud xAPI steps.",
            supported_modes=[ExecutionMode.SEPARATED, ExecutionMode.ALL_LLM],
            approval_required_by_default=True,
        ),
        ActionRegistryItem(
            intent=Intent.SET_SPEAKERTRACK.value,
            label="SpeakerTrack",
            description="Activate or deactivate SpeakerTrack on the target device.",
            supported_modes=[ExecutionMode.SEPARATED, ExecutionMode.ALL_LLM],
            approval_required_by_default=True,
        ),
        ActionRegistryItem(
            intent=Intent.SET_STANDBY.value,
            label="Standby",
            description="Activate or deactivate standby on the target device.",
            supported_modes=[ExecutionMode.SEPARATED, ExecutionMode.ALL_LLM],
            approval_required_by_default=True,
        ),
        ActionRegistryItem(
            intent=Intent.REBOOT.value,
            label="Reboot",
            description="Restart the target device.",
            supported_modes=[ExecutionMode.SEPARATED],
            approval_required_by_default=True,
        ),
        ActionRegistryItem(
            intent=Intent.FACTORY_RESET.value,
            label="Factory reset",
            description="Reset the device to factory defaults.",
            supported_modes=[ExecutionMode.SEPARATED],
            approval_required_by_default=True,
        ),
    ]
